apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plant
  template:
    metadata:
      labels:
        app: plant
    spec:
      containers:
      - name: backend
        image: gcr.io/YOUR_PROJECT/plant:1.0
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: key
        ports:
        - containerPort: 3000
